spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_ID}
    password: ${MYSQL_PASSWORD}

mail:
  address:
    admin: admin@gmail.com

jwt:
  key: ${jwt.key}
  #?? ???? ??
  access-token-expiration-minutes: 300
  refresh-token-expiration-minutes: 4200

recipes:
  openapi-key: ${recipes.openapi-key}